---
title: "Untitled"
author: "Andres Garcia"
date: "23/11/2022"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Funcion para eliminar acentos}
# define the function
remove.accents <- function(s) {
  
  # 1 character substitutions
  old1 <- "éíóáú"
  new1 <- "eioau"
  s1 <- chartr(old1, new1, s)
  
  # 2 character substitutions 
  old2 <- c("ß")
  new2 <- c("ss")
  s2 <- s1
  
  # finalize the function
  for(i in seq_along(old2)) s2 <- gsub(old2[i], new2[i], s2, fixed = TRUE)
  
  s2
}
```


```{r}
unique(bd_depurada$CLASE)
```


```{r}
prediccion2 <- read.csv("prediccion4.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```
```{r}
prediccion3<- read.csv("prediccion_sin_comuna.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```


```{r}
Base_prediccion_2021 <- subset(prediccion2, (ANO != '2022'))

Base_prediccion_2021$FECHA <- as.Date(Base_prediccion_2021$FECHA)
Base_prediccion_2021$CLASE <- as.factor(Base_prediccion_2021$CLASE)
Base_prediccion_2021$DIA_SEMANA <- as.factor(Base_prediccion_2021$DIA_SEMANA)
Base_prediccion_2021$ANO <- as.integer(Base_prediccion_2021$ANO)
Base_prediccion_2021$FESTIVIDAD <- as.factor(Base_prediccion_2021$FESTIVIDAD)

prediccion_2021 <- predict(object = lm6, newdata = Base_prediccion_2021,
                          type = "response")
prediccion_diaria2021 <- Base_prediccion_2021 %>% 
  mutate(NRO_ACCID = round(prediccion_2021,0))

diario_20_02 <- prediccion_diaria2021 %>%
  group_by(FECHA, DIA_SEMANA, CLASE, FESTIVIDAD,COMUNA) %>%
  dplyr::summarise(NRO_TOTAL_ACCID=NRO_ACCID)

head(diario_20_02, 10)
```
