---
title: "Agrupamiento"
author: "Andres Garcia"
date: "19/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r cars}
library(stringr)
library(dplyr)
library(rgdal)
library(plyr);
library(tidyverse)
library(kableExtra)
library(lubridate)
library(ggplot2)
library(plotly)
library(ggpubr)
library(dummy)
library(readxl)
library(sf)
library(GGally)
library(car)
library(MLmetrics)
library(wordcloud)
library(gplots)
library(R.utils)
library(tm)
library(DescTools)
library(raster)
library(mclust)
library(geosphere)
library(NbClust)
library(factoextra)
library(vegan)
library(qpcR)
library(leaflet)
library(stringi)

```



```{r}
Base_depurada <- read.csv("base_depurada.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```




```{r}
barrios_csv<-read.csv("Catastro_gdb.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```

```{r}
Unido <- inner_join(barrios_csv, Base_depurada, by = c("COMUNA" = "NUMCOMUNA"))

```

```{r}
nueva_base <- Unido %>% filter(ANO >= 2014 & ANO <= 2019) %>% 
  group_by(CODIGO) %>%
  dplyr::summarise(accidentes = n()) %>%
  ungroup()

```

```{r}
nueva_base2 <- Unido %>% filter(ANO >= 2014 & ANO <= 2019) %>% 
  group_by(CODIGO,NOMBRE_BARRIO) %>%
  dplyr::summarise(accidentes = n())%>%
  arrange(NOMBRE_BARRIO)
```


```{r}
catastro <- read_sf("Catastro_gdb.shp")
```

```{r}
catastro$CODIGO <- as.numeric(as.character(barrios_csv$CODIGO))

```


```{r}
mapa <- inner_join(catastro, nueva_base, by = c("CODIGO" = "CODIGO"))



```

```{r}
mypal <- colorNumeric(palette = c("#000000","#280100","#3D0201","#630201","#890100","#B00100","#DD0100","#F50201",
                                   "#FF5F5E","#FF7A79","#FF9796","#FEB1B0","#FDC9C8", "#FFE5E4"), domain = mapa$accidentes, reverse = T)
```




```{r}
leaflet() %>% addPolygons(data = mapa, color = "#0A0A0A", opacity = 0.6, weight = 1, fillColor = ~mypal(mapa$accidentes),
                          fillOpacity = 0.6, label = ~NOMBRE_BAR,
                          highlightOptions = highlightOptions(color = "black", weight = 3, bringToFront = T, opacity = 1),
                          popup = paste("Barrio: ", mapa$NOMBRE_BAR, "<br>", "Accidentes: ", mapa$accidentes, "<br>")) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addLegend(position = "bottomright", pal = mypal, values = mapa$accidentes, title = "Accidentes", opacity = 0.6)
```

```{r}
accidentalidad_comuna<- Base_depurada%>%
  filter(ANO>=2014 && ANO<2019)%>%
  group_by(COMUNA)%>%
  summarise(num=n())
```

```{r}
accidentalidad_comuna
```

```{r Pregunta 4-2}
ggplot(accidentalidad_comuna, aes(x=COMUNA,y=num)) +
  geom_bar(stat="identity")+
  
  theme(axis.text.x = element_text(angle = 90, hjust = 0))+
  geom_hline(aes(yintercept = mean(num)), col = "red")
  
```

```{r}
Base_depurada$LATITUD <- as.numeric(as.character(Base_depurada$LATITUD))
Base_depurada$LONGITUD<- as.numeric(as.character(Base_depurada$LONGITUD))
```

```{r}
geo.dist = function(df) {
  require(geosphere)
  d <- function(i,z){         # z[1:2] contain long, lat
    dist <- rep(0,nrow(z))
    dist[i:nrow(z)] <- distHaversine(z[i:nrow(z),1:2],z[i,1:2])
    return(dist)
  }
  dm <- do.call(cbind,lapply(1:nrow(df),d,df))
  return(as.dist(dm))
}
```

```{r}
df <- data.frame(long = Base_depurada$LONGITUD, lat = Base_depurada$LATITUD, barrios = Base_depurada$BARRIO)
```


```{r}
df1 <- df[1:1000, ]
d <- geo.dist(df1)
hc <- hclust(d)
plot(hc, main = "Dendograma", col = "black")
```

```{r}
df1$clust <- cutree(hc, k = 6)
head(df1,10)
```

```{r}
s <- shapefile("planeacion_gdb.shp")
map.df1 <- (s)
ggplot(map.df1)+
  geom_path(aes(x=long, y=lat, group=group))+
  geom_point(data=df1, aes(x=long, y=lat, color=factor(clust)), size=4)+
  scale_color_discrete("Cluster")+
  coord_fixed()
```



```{r}
s <- shapefile("Barrio_Vereda.shp")
map.df1 <- (s)
ggplot(map.df1)+
  geom_path(aes(x=long, y=lat, group=group))+
  geom_point(data=df1, aes(x=long, y=lat, color=factor(clust)), size=4)+
  scale_color_discrete("Cluster")+
  coord_fixed()
```
Colisiones con peatones 

```{r}
#Numero de accidentes por Barrio
datos_cluster <- Base_depurada %>% group_by(BARRIO) %>% dplyr::count(name = "TOTAL_ACCIDENTES")

#Número de accidentes por barrio, según gravedad almacenado en 'df'
df <- as.matrix(table(Base_depurada$BARRIO, Base_depurada$GRAVEDAD))
df <- data.frame(Con_heridos = df[,1], Con_muertos = df[,2], Solo_danos = df[,3])

#Escalamiento y centrado de la base de datos.
scaled_data = as.matrix(scale(df))
head(scaled_data, 10)
kmm = kmeans(scaled_data, 5, nstart = 50, iter.max = 15 )
```

```{r}
kmm = kmeans(scaled_data, 5, nstart = 50, iter.max = 15 )
```


```{r}
set.seed(20221119)
k.max <- 10
datos <- scaled_data
wss <- sapply(2:k.max, 
              function(k){kmeans(datos, k, nstart = 50, iter.max = 15 )$tot.withinss})
plot(2:k.max, wss, 
     type = "b", pch = 19, frame = FALSE,
     xlab = "Número de Clusters (k)",
     ylab = "WSS Total", 
     main = "Método del Codo", col="forestgreen")
```

```{r}
nb <- NbClust(scaled_data, diss=NULL, distance = "euclidean", 
              min.nc=4, max.nc=8, method = "kmeans", 
              index = "all", alphaBeale = 0.1)
```

```{r}
hist(nb$Best.nc[1,], breaks = max(na.omit(nb$Best.nc[1,])), main = "Histograma del K óptimo ", xlab = "K", ylab = "Frecuencia", col="darkorchid4")
```

```{r}
fviz_nbclust(scaled_data, kmeans, method = c("silhouette"))
```
```{r}
fviz_nbclust(scaled_data, kmeans, method = "wss") +
    geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Método del Codo")
```

```{r}
set.seed(321)
fviz_nbclust(scaled_data, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
```

```{r}
kmm = kmeans(scaled_data, 4, nstart = 50, iter.max = 15 )

df_clust <- data.frame(Con_heridos = df[,1], Con_muertos = df[,2], Solo_danos = df[,3], kmm$cluster)
head(df_clust, 10)
```
```{r}
dfclust_clust1 <- df_clust[df_clust$kmm.cluster == 1, ]
dfclust_clust1$total <- rowSums(dfclust_clust1[,1:3])
sum(dfclust_clust1$Con_heridos)
```

```{r}
sum(dfclust_clust1$Con_muertos)
```

```{r}
sum(dfclust_clust1$Solo_danos)
```

```{r}
sum(dfclust_clust1$total)
```

```{r}
dfclust_clust2 <- df_clust[df_clust$kmm.cluster == 2, ]
dfclust_clust2$total <- rowSums(dfclust_clust2[,1:3])
sum(dfclust_clust2$Con_heridos)
sum(dfclust_clust2$Con_muertos)
sum(dfclust_clust2$Solo_danos)
sum(dfclust_clust2$total)

```

```{r}
dfclust_clust3 <- df_clust[df_clust$kmm.cluster == 3, ]
dfclust_clust3$total <- rowSums(dfclust_clust3[,1:3])
sum(dfclust_clust3$Con_heridos)
sum(dfclust_clust3$Con_muertos)
sum(dfclust_clust3$Solo_danos)
sum(dfclust_clust3$total)

```
```{r}
dfclust_clust4 <- df_clust[df_clust$kmm.cluster == 4, ]
dfclust_clust4$total <- rowSums(dfclust_clust4[,1:3])
sum(dfclust_clust4$Con_heridos)
sum(dfclust_clust4$Con_muertos)
sum(dfclust_clust4$Solo_danos)
sum(dfclust_clust4$total)

```
```{r}
df_clustx<-df_clust%>%
  mutate(nivel_acc=kmm.cluster)
```

```{r}
df_clustx$nivel_acc[df_clustx$nivel_acc == 1] <- 'Grupo 1'
df_clustx$nivel_acc[df_clustx$nivel_acc == 2] <- 'Grupo 2'
df_clustx$nivel_acc[df_clustx$nivel_acc == 3] <- 'Grupo 3'
df_clustx$nivel_acc[df_clustx$nivel_acc == 4] <- 'Grupo 4'
```

```{r}
write.csv(df_clustx,"prueba.csv", row.names = TRUE)
```

```{r}
base_mapa <- read.csv("rrr.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```

```{r}
write.csv(nueva_base2,"prueba2.csv", row.names = TRUE)
```

```{r}
base_mapa2 <- read.csv("prueba2.csv", dec=",", header=T,sep=",", encoding = "UTF-8")
```

```{r}
ahhh<-nueva_base2
```

```{r}
mapa_def<-base_mapa%>%
  arrange(Barrio)
```


```{r}

nombre_de_barrio<-iconv(ahhh$NOMBRE_BARRIO,from="UTF-8",to="ASCII//TRANSLIT")
codigo_barrio<-iconv(ahhh$CODIGO,from="UTF-8",to="ASCII//TRANSLIT")


```

```{r}
prueba_def<-data.frame(codigo_barrio,nombre_de_barrio)
```

```{r}
prueba_def<-prueba_def%>%
  arrange(nombre_de_barrio)
```


```{r}
writexl::write_xlsx(base_mapa,"mapa.xlsx")
```

```{r}
maparrr <- inner_join(base_mapa, prueba_def, by = c("Barrio" = "nombre_de_barrio"))
mapaxxx <- full_join(base_mapa, prueba_def, by = c("Barrio" = "nombre_de_barrio"))
```

```{r}
#Se vuelve a utlizar catastro para este mapa

#Se importó el archivo .xlsx basemapa

catastro$CODIGO <- as.numeric(as.character(catastro$CODIGO))



```

```{r}
maparrr$codigo_barrio <- as.numeric(as.character(maparrr$codigo_barrio))

```


```{r}
#Se utilizó 'inner join' de nuevo para unir dos bases y para así luego generar mapa

mapa02 <- inner_join(catastro, maparrr, by = c("CODIGO" = "codigo_barrio"))

colorgrupos <- c("#00FF66", "#CCFF00", "#FF0000", "#0066FF")
mapa02$colores <- ifelse(mapa02$kmm.cluster == "1", "#00FF66",
                            ifelse(mapa02$kmm.cluster == "2", "#CCFF00",
                                   ifelse(mapa02$kmm.cluster == "3", "#FF0000",
                                          ifelse(mapa02$kmm.cluster == "4", "#0066FF",0))))

#Mapa final
```



```{r}
leaflet() %>% addPolygons(data = mapa02, opacity = 0.4, color = "#545454",weight = 1, fillColor = mapa02$colores,
                          fillOpacity = 0.4, label = ~NOMBRE_BAR,
                          highlightOptions = highlightOptions(color = "#262626", weight = 3, bringToFront = T, opacity = 1),
                          popup = paste("Barrio: ", mapa02$NOMBRE_BAR, "<br>", "Grupo: ", mapa02$kmm.cluster, "<br>", "Número de Accidentes con heridos: ", mapa02$Con_heridos, "<br>", "Número de Accidentes con muertos: ", mapa02$Con_muertos, "<br>", "Número de Accidentes con solo daños: ", mapa02$Solo_danos)) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addLegend(position = "bottomright", colors = colorgrupos, labels = c("Grupo 1: Accidentalidad Moderada", "Grupo 2: Accidentalidad Baja", "Grupo 3: Accidentalidad Alta", "Grupo 4: Accidentalidad Media-Alta"))
```


